// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity >=0.6.11;

interface IBrax {
  function COLLATERAL_RATIO_PAUSER() external view returns (bytes32);
  function DEFAULT_ADMIN_ADDRESS() external view returns (address);
  function DEFAULT_ADMIN_ROLE() external view returns (bytes32);
  function addPool(address poolAddress ) external;
  function allowance(address owner, address spender ) external view returns (uint256);
  function approve(address spender, uint256 amount ) external returns (bool);
  function balanceOf(address account ) external view returns (uint256);
  function burn(uint256 amount ) external;
  function burnFrom(address account, uint256 amount ) external;
  function collateralRatioPaused() external view returns (bool);
  function controllerAddress() external view returns (address);
  function creatorAddress() external view returns (address);
  function decimals() external view returns (uint8);
  function decreaseAllowance(address spender, uint256 subtractedValue ) external returns (bool);
  function wbtcBtcConsumerAddress() external view returns (address);
  function braxWbtcOracleAddress() external view returns (address);
  function braxInfo() external view returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256);
  function braxPools(address ) external view returns (bool);
  function braxPoolsArray(uint256 ) external view returns (address);
  function braxPrice() external view returns (uint256);
  function braxStep() external view returns (uint256);
  function bxsAddress() external view returns (address);
  function bxsWbtcOracleAddress() external view returns (address);
  function bxsPrice() external view returns (uint256);
  function genesisSupply() external view returns (uint256);
  function getRoleAdmin(bytes32 role ) external view returns (bytes32);
  function getRoleMember(bytes32 role, uint256 index ) external view returns (address);
  function getRoleMemberCount(bytes32 role ) external view returns (uint256);
  function globalCollateralValue() external view returns (uint256);
  function globalCollateralRatio() external view returns (uint256);
  function grantRole(bytes32 role, address account ) external;
  function hasRole(bytes32 role, address account ) external view returns (bool);
  function increaseAllowance(address spender, uint256 addedValue ) external returns (bool);
  function lastCallTime() external view returns (uint256);
  function mintingFee() external view returns (uint256);
  function name() external view returns (string memory);
  function ownerAddress() external view returns (address);
  function poolBurnFrom(address bAddress, uint256 bAmount ) external;
  function poolMint(address mAddress, uint256 mAmount ) external;
  function priceBand() external view returns (uint256);
  function priceTarget() external view returns (uint256);
  function redemptionFee() external view returns (uint256);
  function refreshCollateralRatio() external;
  function refreshCooldown() external view returns (uint256);
  function removePool(address poolAddress ) external;
  function renounceRole(bytes32 role, address account ) external;
  function revokeRole(bytes32 role, address account ) external;
  function setController(address _controllerAddress ) external;
  function setWBTCBTCOracle(address _wbtcBtcConsumerAddress ) external;
  function setBRAXWBtcOracle(address _brax_oracle_addr, address _wbtcAddress ) external;
  function setBXSAddress(address _fxs_address ) external;
  function setBXSBtcOracle(address _bxsOracleAddr, address _wbtcAddress ) external;
  function setBraxStep(uint256 _newStep ) external;
  function setMintingFee(uint256 minFee ) external;
  function setOwner(address _ownerAddress ) external;
  function setPriceBand(uint256 _priceBand ) external;
  function setPriceTarget(uint256 _newPriceTarget ) external;
  function setRedemptionFee(uint256 redFee ) external;
  function setRefreshCooldown(uint256 _newCooldown ) external;
  function setTimelock(address newTimelock ) external;
  function symbol() external view returns (string memory);
  function timelock_address() external view returns (address);
  function toggleCollateralRatio() external;
  function totalSupply() external view returns (uint256);
  function transfer(address recipient, uint256 amount ) external returns (bool);
  function transferFrom(address sender, address recipient, uint256 amount ) external returns (bool);
  function wbtcAddress() external view returns (address);
}